### ISSUE TITLE
Bluedroid wrapper crate

### ISSUE THREAD

**Issue by persello** [esp-rs/awesome-esp-rust#9]
Hello,
I recently published a [wrapper](https://github.com/pulse-loop/bluedroid) for Bluedroid.
Do you also accept driver crates? I think it might be useful, but I only see binary crates and examples in the list.
The crate uses `std`.

**Comment by MabezDev** [comment]
This is amazing, nice work! We'd love to have this on the list. If you wouldn't mind submitting a PR that would be awesome :)
